version: "3.8"

services:
  web:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.runserver 0.0.0.0:8000"